import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <NavBar />
          <div className="flex text-lg pt-8 px-20 justify-center text-center">
            {children}
          </div>
        </body>
    </html>
  );
}